'use strict';

const extensionDetails = {
  shield: 'When on, the session cancels listed ad-network requests before they load and hides leftover overlay slots on the page. This is a RAM-only request filter, not a store add-on.',
  ghost: 'Turning this on forces the isolated session through the local SOCKS5 tunnel and denies camera, location, and screen-share prompts. Open jumps to the Ghost control.',
  guvenlik: 'The permission handler rejects microphone, camera, and display-capture for every guest tab while this stays on. Sites see a hard deny, not a prompt.',
  hunter: 'Enables the video context-menu downloader and yt-dlp/ffmpeg path for the current page. Open shows the Downloads overlay.',
  cookies: 'On each third-party request the session strips Cookie and Set-Cookie so trackers cannot keep a cross-site token in this RAM partition.',
  dnt: 'Adds a DNT: 1 request header to every http(s) call from this session. The site can still ignore it; the header is still sent.',
  ua: 'Replaces the outgoing User-Agent with a common Chrome string so sites see a generic desktop client instead of this build’s default.',
  models: 'This is the local model/agent chat for the session, not a toggleable add-on. Open the AI sidebar from here.',
  'canvas-poisoner': 'Injects a canvas getImageData hook that flips a few pixels so canvas hashes change between loads. Reloading a tab reapplies the hook.',
  'siyuan-bridge': 'Routes recalled notes into chat from the Brain provider you picked (SiYuan or Obsidian). Open the Memory Bridge page to choose the vault or endpoint.',
  'human-jitter': 'Agent click/input paths wait a short random delay so automation does not fire on a perfect clock. Only affects CDP/agent actions, not your mouse.',
  'dead-man-switch': 'Watches the default gateway. If it changes, the session starts the Excommunicado wipe. Leave this off unless you want that automatic trigger.',
  'web3-shield': 'Injects a stub so pages cannot quietly probe window.ethereum or similar wallet objects in this session.',
  'shadow-dom-pierce': 'Forces attachShadow({mode:"open"}) so agents can read closed components on the current tab.',
  'markdown-dom': 'Agent "read page" calls return a Markdown-stripped article instead of raw innerText.',
  'ui-code-extract': 'Exposes window.__agentExtractUi() for the selected node’s tag, id, classes, and HTML slice.',
  'infinite-scroll': 'Gives agents window.__agentScrollTick() to page down infinite feeds without a human scroll.',
  'table-parser': 'Gives agents window.__agentTables() which dumps visible HTML tables as row arrays.',
  'xhr-hunter': 'Hooks fetch, XHR, and WebSocket on the tab and keeps the last JSON payloads in memory for the agent.',
  'json-form-fill': 'Agents can call window.__agentFillJson(data) to map keys onto named inputs on the current form.',
  'proxy-rotate': 'Each new agent-owned tab picks the next SOCKS/HTTP rule from the session proxy pool.',
  'webgl-inspector': 'Exposes window.__agentWebglMeta() so agents can read canvas size and renderer strings.',
  'media-source': 'Exposes window.__agentMediaSources() to list real src/currentSrc values on media elements.',
  'n8n-webhook': 'When armed, selected page events POST to the local n8n loopback webhook you configured.',
  'lm-studio-port': 'Long page extracts are summarized on the local LLM first so the agent receives a shorter payload.',
  'memory-block': 'Writes notable findings into the in-RAM memory block list (and SiYuan when that bridge is also on).',
  'cursor-ide-bridge': 'Keeps scraped code snippets in the session list that the local workspace bridge can read.',
  'tab-orchestrator': 'When more than 10 guest tabs are open, inactive ones are background-throttled so RAM stays bounded.',
  'headless-mode': 'Hides and throttles inactive guest views while agents work, so the GPU is not painting every tab.',
  'input-simulator': 'Agent click/type paths go through CDP with human-like delays instead of instant JS clicks.',
  'rate-limit-guard': 'A 429/503 or Cloudflare challenge pauses further agent actions on that tab for 20 seconds.',
  'sandbox-isolator': 'New agent-owned tabs get their own in-memory partition so cookies do not leak across tasks.',
  'excommunicado-lock': 'Repeated agent errors on a tab destroy that tab and return a Failed signal instead of looping.',
  'webrtc-leak-blocker': 'On top of the session UDP policy, this stubs RTCPeerConnection iceServers on the page so WebRTC cannot advertise LAN candidates.',
  'canvas-fingerprint-defender': 'Same engine hook as Canvas Poisoner: pixel noise on getImageData. Use either card; they share one switch.',
  'audiocontext-spoofer': 'Wraps AudioContext so analyser fingerprints pick up a tiny frequency offset instead of a stable hardware hash.',
  'battery-api-randomizer': 'Replaces navigator.getBattery with a fixed dummy pack so charge level cannot identify the device.',
  'geolocation-shifter': 'Denies the real Geolocation permission and answers page calls with a pinned Istanbul coordinate.',
  'referrer-stripper-pro': 'Deletes Referer on every outbound request in this session, including first-party navigations.',
  'etag-cache-cleanser': 'Strips If-None-Match / If-Modified-Since on the way out and ETag / Last-Modified on the way back so cache tokens cannot track the tab.',
  'dom-storage-sandboxing': 'Prefixes localStorage and sessionStorage keys with the hostname so page scripts cannot read a shared dump.',
  'keystroke-anonymizer': 'Keyboard listeners the page attaches are delayed 20–60ms so timing biometrics smear.',
  'doh-forcer': 'Switches Chromium’s resolver to DNS-over-HTTPS via Cloudflare. Toggle off to return to automatic DNS.',
  'user-agent-rotator': 'Same engine hook as Identity mask: a common Chrome UA on every request. The two cards share one switch.',
  'third-party-cookie-annihilator': 'Same engine hook as Cookie cutter: third-party Cookie/Set-Cookie are dropped. Shared switch.',
  'link-tracking-parameter-remover': 'Redirects requests that carry utm_*, fbclid, gclid, and similar query keys to the same URL with those keys removed.',
  'ping-request-blocker': 'Cancels resourceType=ping so <a ping> and sendBeacon-style pings never leave the session.',
  'idle-ram-purger': 'Every 30s, guest tabs idle more than two minutes get background throttling and the session cache is cleared.',
  'wayback-machine-fast-fetcher': 'On load, the session asks archive.org whether this exact URL has a snapshot and stores it on window.__agentCatalog.wayback.',
  'shodan-passive-ip-scanner': 'Resolves the current host and reads the public InternetDB record (ports/tags) into window.__agentCatalog.shodan. No active port scan of the remote host.',
  'exif-metadata-viewer': 'Collects visible image URLs and intrinsic sizes into window.__agentCatalog.exif so you can inspect what the page actually loaded.',
  'subdomain-enumeration-helper': 'Walks href/src on the current document and lists hostnames that belong to this site’s root.',
  'hidden-endpoint-discoverer': 'Regex-scans the current HTML for /api/… and quoted paths, then stores up to 40 hits on window.__agentCatalog.endpoints.',
  'crypto-address-highlighter': 'Wraps likely BTC/ETH strings on the page in a mark so wallet addresses are visible at a glance.',
  'social-media-handle-cross-referencer': 'Collects @handles from visible text and builds X/GitHub/Reddit lookup URLs in window.__agentCatalog.handles.',
  'bgp-route-visualizer': 'Queries RIPEstat for the current hostname and stores prefix/ASN data on window.__agentCatalog.bgp.',
  'public-s3-bucket-tester': 'Lists S3/GCS/R2 URLs already present on this page (no extra discovery). Agents can HEAD those URLs next.',
  'jwt-decoder-verifier': 'Scans localStorage/sessionStorage for JWT-shaped strings and decodes the payload into window.__agentCatalog.jwt.',
  'http-header-analyzer': 'Remembers CSP/HSTS/XFO/Referrer-Policy from the main-frame response and injects that grade into the page catalog.',
  'dark-web-onion-status-checker': 'Collects .onion links already on the page. It does not open Tor; it only lists what the document already linked.',
  'reverse-image-search-matrix': 'Adds a context-menu item on images that opens Google Lens, Yandex, and TinEye tabs for that image URL.',
  'phishing-domain-homograph-detector': 'If the hostname mixes ASCII with other scripts, a red banner is pinned on the page.',
  'ssl-tls-certificate-deep-inspector': 'Opens a TLS handshake to the current host:443 and stores subject, issuer, and expiry on window.__agentCatalog.tls.',
  'shadow-dom-piercer': 'Same engine hook as Shadow DOM Piercer in Session tools. Shared switch.',
  'xpath-css-selector-generator': 'After you click an element, the shortest CSS path is stored on window.__agentCatalog.selector.',
  'table-to-json-auto-parser': 'Same engine hook as Table & Grid Parser. Shared switch.',
  'infinite-scroll-autopilot': 'Same engine hook as Infinite Scroll Autonomy. Shared switch.',
  'headless-mode-resource-saver': 'Same engine hook as Headless Mode. Shared switch.',
  'captcha-resource-exporter': 'Lists reCAPTCHA/hCaptcha iframes and captcha images already on the page so you can send them to a solver you configure.',
  'human-jitter-cursor-simulator': 'Same engine hook as Ghost Mouse. Shared switch.',
  'rate-limit-auto-pauser': 'Same engine hook as Rate-Limit Guard. Shared switch.',
  'dynamic-proxy-swapper': 'Same engine hook as Dynamic Proxy Rotator. Shared switch.',
  'hidden-form-field-revealer': 'Turns hidden inputs into visible outlined text fields so honeypots and CSRF tokens are readable.',
  'websocket-traffic-interceptor': 'Wraps WebSocket and keeps the last messages in window.__agentWsLog even if XHR Hunter is off.',
  'xhr-fetch-payload-catcher': 'Same engine hook as XHR & WebSocket Hunter. Shared switch.',
  'dom-mutation-logger': 'A MutationObserver records added-node bursts on window.__agentMut so late Ajax injections are visible.',
  'iframe-content-extractor': 'Reads same-origin iframe innerText into window.__agentCatalog.iframes. Cross-origin frames stay empty.',
  'semantic-html-simplifier': 'Copies article/main text into the catalog and, when agents read the page, that cleaner text is preferred over the full DOM dump.',
  'page-to-markdown-converter': 'Same engine hook as Markdown DOM Translator. Shared switch.',
  'generic-llm-api-bridge': 'Chat calls automatically prepend up to 8k characters of the current page so the local/session model sees the tab.',
  'context-window-splitter': 'Agent page-text reads are split into 1800-character chunks with index markers so long articles fit a context window.',
  'system-prompt-injector': 'Every chat turn in this session gets an extra system message that tells the model to stay on page facts.',
  'vision-api-screenshot-sender': 'Uses the existing tab screenshot capture (PNG base64) so a vision model can be fed the current viewport.',
  'vector-db-text-embedder': 'Chunks the page text into 1800-character pieces on window.__agentCatalog.chunks, ready to POST to a store you already run.',
  'autonomous-agent-task-queue': 'Same engine hook as Multi-Tab Orchestrator. Shared switch.',
  'llm-cost-token-estimator': 'Estimates tokens as characters/4 and stores the number on window.__agentCatalog.tokens before you send a payload.',
  'scraping-schema-enforcer': 'Exposes window.__agentEnforceSchema(record, schema) so an agent can reject incomplete scrapes.',
  'multi-agent-swarm-broadcaster': 'Same engine hook as n8n Webhook Trigger. Shared switch.',
  'react-vue-state-inspector': 'Checks #root/#app for React or Vue markers and stores {react, vue} on the page catalog.',
  'graphql-query-visualizer': 'Exposes window.__agentGraphql(query) to list operation names from a pasted GraphQL string.',
  'rest-api-replay-tool': 'Points window.__agentLastRest at the latest captured network payload when XHR Hunter has been collecting.',
  'localhost-port-scanner': 'When you open a tab, the session probes 127.0.0.1 common dev ports (3000, 8080, …) and lists which ones accepted a connection.',
  'regex-search-replace': 'Exposes window.__agentRegexReplace(pattern, replacement) to run a regex across the current body HTML.',
  'base64-hex-url-decoder': 'Right-click a selection to decode base64/URI and copy the result to the clipboard.',
  'css-grid-flexbox-highlighter': 'Outlines computed grid/flex containers so the layout skeleton is visible on the live page.',
  'console-error-aggregator': 'Wraps console.error and keeps the last 40 messages on window.__agentConsole.',
  'indexeddb-localstorage-editor': 'Dumps up to 30 localStorage keys/values into window.__agentCatalog.storage for this origin.',
  'media-source-blob-revealer': 'Same engine hook as Media Source Revealer. Shared switch.',
  'cron-expression-tester': 'Exposes window.__agentCron(expr) to check a 5/6-field cron string.',
  'webassembly-wasm-decompiler': 'Lists .wasm script URLs on the page. It does not run a full WAT decompiler; it surfaces the modules the page already loaded.',
  'network-throttling-simulator': 'Applies Chromium network emulation (400ms RTT, ~50KB/s down) to this session until you turn it off.',
  'broken-link-404-crawler': 'Exposes window.__agentBrokenLinks() with same-origin hrefs so an agent can HEAD them for 404s.',
  'page-load-performance-profiler': 'Reads navigation timing and stores DOMContentLoaded / load durations on window.__agentCatalog.perf.',
};

if (typeof module === 'object' && module.exports) {
  module.exports = extensionDetails;
}
