'use strict';

const agentExtensions = [
  { id: 'webrtc-leak-blocker', name: 'WebRTC Leak Blocker', description: 'Cuts UDP traffic so the local network IP is not leaked through WebRTC.', category: 'opsec', active: false },
  { id: 'canvas-fingerprint-defender', name: 'Canvas Fingerprint Defender', description: 'Adds random noise to canvas pixel drawing so hardware tracking breaks down.', category: 'opsec', active: false },
  { id: 'audiocontext-spoofer', name: 'AudioContext Spoofer', description: 'Masks the sound-card hardware fingerprint exposed by AudioContext.', category: 'opsec', active: false },
  { id: 'battery-api-randomizer', name: 'Battery API Randomizer', description: 'Spoofs battery state and charge level reported to websites.', category: 'opsec', active: false },
  { id: 'geolocation-shifter', name: 'Geolocation Shifter', description: 'Pins the HTML5 Geolocation API to random world coordinates.', category: 'opsec', active: false },
  { id: 'referrer-stripper-pro', name: 'Referrer Stripper Pro', description: 'Strips HTTP Referer headers completely when leaving a site.', category: 'opsec', active: false },
  { id: 'etag-cache-cleanser', name: 'ETag Cache Cleanser', description: 'Resets cache identifiers so servers cannot track the device through ETags.', category: 'opsec', active: false },
  { id: 'dom-storage-sandboxing', name: 'DOM Storage Sandboxing', description: 'Locks each tab into its own LocalStorage and IndexedDB area.', category: 'opsec', active: false },
  { id: 'keystroke-anonymizer', name: 'Keystroke Anonymizer', description: 'Normalizes keystroke timing to block biometric keyboard analysis.', category: 'opsec', active: false },
  { id: 'doh-forcer', name: 'DNS over HTTPS (DoH) Forcer', description: 'Sends DNS queries over an encrypted channel to stop local DNS leaks.', category: 'opsec', active: false },
  { id: 'user-agent-rotator', name: 'User-Agent Rotator', description: 'Rotates OS and browser identity on each new connection.', category: 'opsec', active: false },
  { id: 'third-party-cookie-annihilator', name: 'Third-Party Cookie Annihilator', description: 'Rejects cross-site cookies at RAM level for this session.', category: 'opsec', active: false },
  { id: 'link-tracking-parameter-remover', name: 'Link Tracking Parameter Remover', description: 'Strips UTM, fbclid, gclid, and similar trackers from URLs in flight.', category: 'opsec', active: false },
  { id: 'ping-request-blocker', name: 'Ping Request Blocker', description: 'Stops background tracking pings sent through <a ping>.', category: 'opsec', active: false },
  { id: 'idle-ram-purger', name: 'Idle RAM Purger', description: 'Wipes memory traces from tabs that sit idle past a short timeout.', category: 'opsec', active: false },
  { id: 'wayback-machine-fast-fetcher', name: 'Wayback Machine Fast-Fetcher', description: 'Pulls archived versions of the current URL from the Wayback Machine.', category: 'osint', active: false },
  { id: 'shodan-passive-ip-scanner', name: 'Shodan Passive IP Scanner', description: 'Looks up the visited host IP in Shodan without active probing.', category: 'osint', active: false },
  { id: 'exif-metadata-viewer', name: 'EXIF Metadata Viewer', description: 'Shows hidden camera, GPS, and date data inside page images.', category: 'osint', active: false },
  { id: 'subdomain-enumeration-helper', name: 'Subdomain Enumeration Helper', description: 'Passively discovers subdomains of the current site.', category: 'osint', active: false },
  { id: 'hidden-endpoint-discoverer', name: 'Hidden Endpoint Discoverer', description: 'Finds hidden API routes inside JavaScript with regex scans.', category: 'osint', active: false },
  { id: 'crypto-address-highlighter', name: 'Crypto Address Highlighter', description: 'Highlights likely Bitcoin and Ethereum wallet addresses on the page.', category: 'osint', active: false },
  { id: 'social-media-handle-cross-referencer', name: 'Social Media Handle Cross-Referencer', description: 'Searches found usernames across other public platforms.', category: 'osint', active: false },
  { id: 'bgp-route-visualizer', name: 'BGP Route Visualizer', description: 'Charts how packets to the host are routed across the public internet.', category: 'osint', active: false },
  { id: 'public-s3-bucket-tester', name: 'Public S3 Bucket Tester', description: 'Checks whether media-hosting cloud buckets are left publicly open.', category: 'osint', active: false },
  { id: 'jwt-decoder-verifier', name: 'JWT Decoder & Verifier', description: 'Decodes JSON Web Tokens in LocalStorage and inspects their signature shape.', category: 'osint', active: false },
  { id: 'http-header-analyzer', name: 'HTTP Header Analyzer', description: 'Grades security headers such as CSP and HSTS from the server.', category: 'osint', active: false },
  { id: 'dark-web-onion-status-checker', name: 'Dark Web Onion Status Checker', description: 'Tests whether .onion links on the page appear online.', category: 'osint', active: false },
  { id: 'reverse-image-search-matrix', name: 'Reverse Image Search Matrix', description: 'Sends a page image to several reverse-image engines at once.', category: 'osint', active: false },
  { id: 'phishing-domain-homograph-detector', name: 'Phishing Domain Homograph Detector', description: 'Flags look-alike URL characters such as Cyrillic spoofs.', category: 'osint', active: false },
  { id: 'ssl-tls-certificate-deep-inspector', name: 'SSL/TLS Certificate Deep Inspector', description: 'Reports the certificate chain and encryption strength in detail.', category: 'osint', active: false },
  { id: 'shadow-dom-piercer', name: 'Shadow DOM Piercer', description: 'Lets automation read closed web components (shadow-root).', category: 'scrape', active: false },
  { id: 'xpath-css-selector-generator', name: 'XPath & CSS Selector Generator', description: 'Builds the shortest durable selector for a clicked element.', category: 'scrape', active: false },
  { id: 'table-to-json-auto-parser', name: 'Table-to-JSON Auto-Parser', description: 'Turns complex HTML tables into structured JSON arrays.', category: 'scrape', active: false },
  { id: 'infinite-scroll-autopilot', name: 'Infinite Scroll Autopilot', description: 'Auto-scrolls while scraping with human-like pacing.', category: 'scrape', active: false },
  { id: 'headless-mode-resource-saver', name: 'Headless Mode Resource Saver', description: 'Pauses page render during autonomous jobs to save CPU.', category: 'scrape', active: false },
  { id: 'captcha-resource-exporter', name: 'CAPTCHA Resource Exporter', description: 'Exports reCAPTCHA audio and image challenges for an external solver API you configure.', category: 'scrape', active: false },
  { id: 'human-jitter-cursor-simulator', name: 'Human Jitter Cursor Simulator', description: 'Adds random curves and human-like delays to automated clicks.', category: 'scrape', active: false },
  { id: 'rate-limit-auto-pauser', name: 'Rate-Limit Auto-Pauser', description: 'Pauses scraping when 429 Too Many Requests responses appear.', category: 'scrape', active: false },
  { id: 'dynamic-proxy-swapper', name: 'Dynamic Proxy Swapper', description: 'Swaps the SOCKS5/HTTP proxy tunnel in milliseconds after a block.', category: 'scrape', active: false },
  { id: 'hidden-form-field-revealer', name: 'Hidden Form Field Revealer', description: 'Makes display:none honeypot inputs visible in the session.', category: 'scrape', active: false },
  { id: 'websocket-traffic-interceptor', name: 'WebSocket Traffic Interceptor', description: 'Captures live streams (markets, chat) as JSON.', category: 'scrape', active: false },
  { id: 'xhr-fetch-payload-catcher', name: 'XHR/Fetch Payload Catcher', description: 'Skims raw API payloads without waiting on the page UI.', category: 'scrape', active: false },
  { id: 'dom-mutation-logger', name: 'DOM Mutation Logger', description: 'Tracks elements injected later by Ajax.', category: 'scrape', active: false },
  { id: 'iframe-content-extractor', name: 'iframe Content Extractor', description: 'Extracts readable iframe text that the session is allowed to access.', category: 'scrape', active: false },
  { id: 'semantic-html-simplifier', name: 'Semantic HTML Simplifier', description: 'Strips div soup and leaves semantic HTML for LLMs.', category: 'scrape', active: false },
  { id: 'page-to-markdown-converter', name: 'Page-to-Markdown Converter', description: 'Converts articles into Markdown that models read cleanly.', category: 'ai', active: false },
  { id: 'generic-llm-api-bridge', name: 'Generic LLM API Bridge', description: 'Sends page text to any REST LLM API the user defines.', category: 'ai', active: false },
  { id: 'context-window-splitter', name: 'Context Window Splitter', description: 'Splits long text into token-safe chunks.', category: 'ai', active: false },
  { id: 'system-prompt-injector', name: 'System Prompt Injector', description: 'Applies a user-supplied system prompt when talking to web chat UIs in this session.', category: 'ai', active: false },
  { id: 'vision-api-screenshot-sender', name: 'Vision API Screenshot Sender', description: 'Crops a selected DOM area and sends it as base64 to a vision model.', category: 'ai', active: false },
  { id: 'vector-db-text-embedder', name: 'Vector DB Text Embedder', description: 'Prepares text for external vector stores such as Chroma or Pinecone.', category: 'ai', active: false },
  { id: 'autonomous-agent-task-queue', name: 'Autonomous Agent Task Queue', description: 'Queues tab jobs for agents that attach over CDP.', category: 'ai', active: false },
  { id: 'llm-cost-token-estimator', name: 'LLM Cost & Token Estimator', description: 'Estimates token cost before a payload is sent to an API.', category: 'ai', active: false },
  { id: 'scraping-schema-enforcer', name: 'Scraping Schema Enforcer', description: 'Checks scraped records against the JSON schema an agent expects.', category: 'ai', active: false },
  { id: 'multi-agent-swarm-broadcaster', name: 'Multi-Agent Swarm Broadcaster', description: 'Publishes the current tab payload to external automation webhooks.', category: 'ai', active: false },
  { id: 'react-vue-state-inspector', name: 'React/Vue State Inspector', description: 'Surfaces framework component trees on production sites.', category: 'devtools', active: false },
  { id: 'graphql-query-visualizer', name: 'GraphQL Query Visualizer', description: 'Turns packed GQL payloads into readable nodes.', category: 'devtools', active: false },
  { id: 'rest-api-replay-tool', name: 'REST API Replay Tool', description: 'Edits and resends captured network requests (session Postman).', category: 'devtools', active: false },
  { id: 'localhost-port-scanner', name: 'Localhost Port Scanner', description: 'Detects common local dev ports such as 3000 and 8080 on this machine.', category: 'devtools', active: false },
  { id: 'regex-search-replace', name: 'Regex Search & Replace', description: 'Runs regex find/replace across the current DOM.', category: 'devtools', active: false },
  { id: 'base64-hex-url-decoder', name: 'Base64/Hex/URL Decoder', description: 'Decodes encoded text from a context-menu selection.', category: 'devtools', active: false },
  { id: 'css-grid-flexbox-highlighter', name: 'CSS Grid/Flexbox Highlighter', description: 'Draws neon layout bounds so the UI skeleton is visible.', category: 'devtools', active: false },
  { id: 'console-error-aggregator', name: 'Console Error Aggregator', description: 'Categorizes JavaScript errors on the page and exports them.', category: 'devtools', active: false },
  { id: 'indexeddb-localstorage-editor', name: 'IndexedDB & LocalStorage Editor', description: 'Reads and writes session storage stores directly.', category: 'devtools', active: false },
  { id: 'media-source-blob-revealer', name: 'Media Source Blob Revealer', description: 'Finds the real buffer behind blob:http media sources.', category: 'devtools', active: false },
  { id: 'cron-expression-tester', name: 'CRON Expression Tester', description: 'Validates CRON syntax and shows the next run time.', category: 'devtools', active: false },
  { id: 'webassembly-wasm-decompiler', name: 'WebAssembly (Wasm) Decompiler', description: 'Turns .wasm files into readable WAT text.', category: 'devtools', active: false },
  { id: 'network-throttling-simulator', name: 'Network Throttling Simulator', description: 'Simulates poor connections to test site performance.', category: 'devtools', active: false },
  { id: 'broken-link-404-crawler', name: 'Broken Link (404) Crawler', description: 'Finds dead links across the current domain.', category: 'devtools', active: false },
  { id: 'page-load-performance-profiler', name: 'Page Load Performance Profiler', description: 'Reports DOMContentLoaded and Load times in milliseconds.', category: 'devtools', active: false },
];

if (typeof module === 'object' && module.exports) {
  module.exports = agentExtensions;
}
